# Workflow: Merge MALTSSQA to RELEASE
# Summary:
# This workflow merges changes from the MALTSSQA branch into the RELEASE092025 branch.
# It identifies changed files since the last successful merge, generates delta metadata files,
# applies non-deletion changes, commits them, and updates the SHA reference for future merges.

name: Update SHA ID 
on:
  pull_request:
    types: [closed]
    branches:
      - RELEASE092025
    paths:
      - 'force-app/main/default/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: write

jobs:
  Merge:
    runs-on: uhg-runner
    environment: RELEASE
    steps:
      # Checkout the target RELEASE branch
      - name: Checkout target branch (RELEASE092025)
        uses: actions/checkout@v4
        with:
          ref: RELEASE092025
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      # Configure Git user details
      - name: Configure Git
        run: |
          git config user.email "maltss_tech@optum.com"
          git config user.name "maltssdeploy"

      # Add remote and fetch source branch (MALTSSQA)
      - name: Add remote and fetch source branch (MALTSSQA)
        run: |
          git remote add source-origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git || true
          git fetch source-origin MALTSSQA

      # Retrieve the last successfully merged SHA
      - name: Get last merged SHA
        id: lastsha
        run: echo "sha=${{ vars.LAST_GOOD_SHA_RELEASE_MERGE }}" >> $GITHUB_OUTPUT

      # Update the SHA variable to track the latest successful merge
      - name: Update SHA ID 
        run: |
          NEW_SHA=$(git rev-parse source-origin/MALTSSQA)
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/environments/RELEASE/variables/LAST_GOOD_SHA_RELEASE_MERGE \
            -f name="LAST_GOOD_SHA_RELEASE_MERGE" \
            -f value="$NEW_SHA"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # Final success message
      - name: Success message
        run: echo "Successfully Updated SHA ID "
