name: Promote to QA
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to merge from (e.g. Dev)'
        required: true
        default: 'Dev'
      target_branch:
        description: 'Target branch to merge into (e.g. QA)'
        required: true
        default: 'QA'
permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: write
env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          token: ${{ secrets.PAT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email "neha.sforce@gmail.com"
          git config --global user.name "Neha Jain"
      - name: Add remote and fetch source branch
        run: |
          git remote add source-origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch source-origin ${{ github.event.inputs.source_branch }}
      - name: Merge source into target
        run: |
          git merge --no-ff source-origin/${{ github.event.inputs.source_branch }} -m "Promote ${{ github.event.inputs.source_branch }} to ${{ github.event.inputs.target_branch }}"
          git push origin HEAD:${{ github.event.inputs.target_branch }}
      - name: Success message
        run: echo "✅ Successfully promoted ${{ github.event.inputs.source_branch }} to ${{ github.event.inputs.target_branch }}"
