name: Promote to QA
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: write
env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: QA
          token: ${{ secrets.PAT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email "neha.sforce@gmail.com"
          git config --global user.name "Neha Jain"
      - name: Add remote and fetch source branch
        run: |
          git remote add source-origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch source-origin Dev
      - name: Merge source into target
        run: |
          git merge --no-ff --allow-unrelated-histories  source-origin/Dev -m "Promote Dev to QA"
          git push source-origin QA
      - name: Success message
        run: echo "✅ Successfully promoted Dev to QA"
